add_newline = true
command_timeout = 1000
format = "[┌─────>](bold green) $username$hostname$directory$line_break[│](bold green) $git_branch$git_status$git_state$line_break[└─](bold green)$character"

[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold fg:214)"

[hostname]
ssh_only = false

[username]
format = "[$user]($style) on "
show_always = true
