# ============================================= #
# Start with defaults from the Sensible plugin  #
# --------------------------------------------- #
run-shell /nix/store/a20bnggicmhqpw0iwnpq4v2fwvb7bfws-tmuxplugin-sensible-unstable-2022-08-14/share/tmux-plugins/sensible/sensible.tmux
# ============================================= #

set  -g default-terminal "screen-256color"
set  -g base-index      1
setw -g pane-base-index 1





set -g status-keys vi
set -g mode-keys   vi







set  -g mouse             off
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       1
set  -g history-limit     2000

# ============================================= #
# Load plugins with Home Manager                #
# --------------------------------------------- #

# tmuxplugin-vim-tmux-navigator
# ---------------------

run-shell /nix/store/ra48i1kfmsndna9y3p154sc88l6ar4bp-tmuxplugin-vim-tmux-navigator-unstable-2022-08-21/share/tmux-plugins/vim-tmux-navigator/vim-tmux-navigator.tmux


# tmuxplugin-gruvbox
# ---------------------

run-shell /nix/store/70zihaa0hj4hzm6z96vz5vjx9xqvsnb0-tmuxplugin-gruvbox-unstable-2022-04-19/share/tmux-plugins/gruvbox/gruvbox-tpm.tmux

# ============================================= #

set-option -g default-shell $HOME/.nix-profile/bin/fish
# set-option -g default-shell $HOME/.nix-profile/bin/zsh

# Update environment on re-attach
set -g update-environment -r

# Renumber windows automatically
set -g renumber-windows on

# Set terminal-overrides as suggested in NVIM :checkhealth
set-option -sa terminal-overrides ',xterm-256color:Tc'

# Set window titles
set-window-option -g automatic-rename on
# set-option -g set-titles on

set-option -g mouse on

# Pane creation
# Split horizontally
bind-key '%' split-window -h -c '#{pane_current_path}'
# Split vertically
bind-key '"' split-window -v -c '#{pane_current_path}'

# Send C-l to clear screen. With vim-tmux-navigator C-l is used to switch to
# left pane
bind C-l send-keys 'C-l'

# Use v to trigger selection and y to copy to clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Undercurl support (https://github.com/eddyekofo94/gruvbox-flat.nvim)
# set -g default-terminal "${TERM}"
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Source tmux Catppuccin Latte theme
# source-file $HOME/.config/tmux/themes/tmux_catppuccin_latte.tmux
# source-file $HOME/.config/tmux/themes/tmux_tokyonight_storm.tmux
source-file $HOME/.config/tmux/themes/gruvbox/tmux-gruvbox-dark.conf
# source-file $HOME/.config/tmux/themes/nightfox/dawnfox.tmux
