# Nightfox Color Palette
# Style: dawnfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dawnfox/nightfox_fish.fish

# Syntax Highlighting Colors
fish_color_normal 575279
fish_color_command 56949f
fish_color_keyword d685af
fish_color_quote ea9d34
fish_color_redirection 575279
fish_color_end d7827e
fish_color_error b463a7
fish_color_param 907aa9
fish_color_comment 9893a5
fish_color_selection --background=d0d8d8
fish_color_search_match --background=d0d8d8
fish_color_operator 618774
fish_color_escape d685af
fish_color_autosuggestion 9893a5

# Completion Pager Colors
fish_pager_color_progress 9893a5
fish_pager_color_prefix 56949f
fish_pager_color_completion 575279
fish_pager_color_description 9893a5
