# Load plugins first - this allows the rest of the config file to override
# any settings coming from the plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/vim-tmux-navigator'
set -g @plugin 'TanglingTreats/tmux-everforest'
set -g @tmux-everforest 'dark-medium'

# Set PATH before running tpm
# set-environment -g PATH "$HOME/.nix-profile/bin $PATH"
run $HOME/.config/tmux/plugins/tpm/tpm

set -g mouse on

# Disable aggressive-resize for iTerm attach mode
setw -g aggressive-resize off

# Set the default shell in tmux windows
set-option -g default-shell $HOME/.nix-profile/bin/fish
# set-option -g default-shell $HOME/.nix-profile/bin/zsh

# Update environment on re-attach
set -g update-environment -r

# Renumber windows automatically
set -g renumber-windows on

# Set terminal-overrides as suggested in NVIM :checkhealth
# set-option -sa terminal-overrides ',xterm-256color:Tc'

# Set the default terminal to "tmux-direct" to support truecolor in neomutt
set-option -g default-terminal "tmux-direct"
set-option -s default-terminal "tmux-direct"

# Set window titles
set-window-option -g automatic-rename on
# set-option -g set-titles on

# Pane creation
## Split horizontally and switch to current directory
bind-key '%' split-window -h -c '#{pane_current_path}'
## Split vertically and switch to current directory
bind-key '"' split-window -v -c '#{pane_current_path}'

# Send C-l to clear screen. With vim-tmux-navigator C-l is used to switch to
# left pane
bind C-l send-keys 'C-l'

# Use v to trigger selection and y to copy to clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Undercurl support (https://github.com/eddyekofo94/gruvbox-flat.nvim)
# set -g default-terminal "${TERM}"
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
# set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Source tmux Catppuccin Latte theme
# source-file $HOME/.config/tmux/themes/tmux_catppuccin_latte.tmux
# source-file $HOME/.config/tmux/themes/tmux_tokyonight_storm.tmux
# source-file $HOME/.config/tmux/themes/gruvbox/tmux-gruvbox-dark.conf
# source-file $HOME/.config/tmux/themes/everforest/tmux-everforest-dark-medium.conf
# source-file $HOME/.config/tmux/themes/nightfox/dawnfox.tmux
# run-shell $HOME/.config/tmux/plugins/tmux-sensible/sensible.tmux
# run-shell $HOME/.config/tmux/plugins/vim-tmux-navigator/vim-tmux-navigator.tmux
