# .bash_profile

# Get the aliases and functions
if [ -f $HOME/.config/bash/bashrc ]; then
	. $HOME/.config/bash/bashrc
fi

# Source proxy environment variables
if [ -f $HOME/.config/bash/proxy_setup.sh ]; then
	. $HOME/.config/bash/proxy_setup.sh
fi

# ----- Disable powerline till line wrapping issue
# is solved
# ------------------------------------------------
# Source powerline configuration
# export POWERLINE_NO_SHELL_PROMPT="TRUE"
#command -v powerline-daemon &>/dev/null
#if [ $? -eq 0 ]; then
	#POWERLINE_BASH_CONTINUATION=1
	#POWERLINE_BASH_SELECT=1
	#. $HOME/.local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
#fi

# Setup SSH agent using keychain
if [ -f $HOME/.config/bash/keychain-setup.sh ]; then
	. $HOME/.config/bash/keychain-setup.sh
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# User specific environment and startup programs
if [ -d $HOME/.local/bin ]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d $HOME/.cargo/bin ]; then
	export PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -e /home/vrkonda/.nix-profile/etc/profile.d/nix.sh ]; then . /home/vrkonda/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
