# .bash_profile

# Source this file only if it has not already been sourced
if [[ -z $BASH_PROFILE_SOURCED ]]; then
	echo "Bash_profile has already been sourced";
	return 1;
fi

# # Get the aliases and functions
# if [ -f $HOME/.config/bash/bashrc ]; then
# 	. $HOME/.config/bash/bashrc
# fi

# # Source proxy environment variables
# if [ -f $HOME/.config/bash/proxy_setup.sh ]; then
# 	. $HOME/.config/bash/proxy_setup.sh
# fi

# ----- Disable powerline till line wrapping issue
# is solved
# ------------------------------------------------
# Source powerline configuration
# export POWERLINE_NO_SHELL_PROMPT="TRUE"
#command -v powerline-daemon &>/dev/null
#if [ $? -eq 0 ]; then
	#POWERLINE_BASH_CONTINUATION=1
	#POWERLINE_BASH_SELECT=1
	#. $HOME/.local/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
#fi

# Setup SSH agent using keychain
if [ -f $HOME/.config/bash/keychain-setup.sh ]; then
	. $HOME/.config/bash/keychain-setup.sh
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# User specific environment and startup programs
if [ -d $HOME/.local/bin ]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d $HOME/.cargo/bin ]; then
	export PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -d $HOME/.yarn/bin ]; then
	export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
fi

# Add vscode to the path
if [ -f ~/.local/vscode/code ]; then
	export PATH="$HOME/.local/vscode:$PATH"
fi

export BASH_PROFILE_SOURCED=1
